"use strict";
const fs=require("fs"), path=require("path"), http=require("http"), crypto=require("crypto");
const {Builder,By,Key,until}=require("selenium-webdriver");
const firefox=require("selenium-webdriver/firefox");
const IPC=path.resolve(process.env.LION_FIREFOX_MEDIATOR_IPC || "\\\\wsl.localhost\\LION-AUTH-LAB\\var\\lib\\sentinelx\\uploads\\lion-mission-control-v3\\firefox-mediator-ipc");
const PROFILE=path.resolve(process.env.LION_FIREFOX_PROFILE || "C:\\Users\\d2j3\\Documents\\Codex\\2026-09-13\\r10-r2-unified\\runtime\\firefox-mediator-profile");
const FIREFOX=process.env.LION_FIREFOX_BINARY || "C:\\Program Files\\Firefox Developer Edition\\firefox.exe";
const EXPECTED_PROJECT=process.env.LION_FIREFOX_PROJECT || "LION_EVOLUSION";
const EXPECTED_CHAT=process.env.LION_FIREFOX_CHAT || "[LION MEDIATOR] SaaS Control Channel";
const TRANSPORT="CHATGPT_FIREFOX_PROJECT_MEDIATED";
const MEDIATOR_ID="LION_FIREFOX_MEDIATOR_R1";
const dirs={inbox:path.join(IPC,"inbox"),outbox:path.join(IPC,"outbox"),journal:path.join(IPC,"journal"),receipts:path.join(IPC,"receipts")};
for(const d of [IPC,PROFILE,...Object.values(dirs)])fs.mkdirSync(d,{recursive:true});
function atomicJson(file,value){const tmp=file+".tmp";fs.writeFileSync(tmp,JSON.stringify(value,null,2),"utf8");fs.renameSync(tmp,file)}
function readJson(file,def=null){try{return JSON.parse(fs.readFileSync(file,"utf8"))}catch{return def}}
function status(state,extra={}){atomicJson(path.join(IPC,"mediator-status.json"),{mediator_id:MEDIATOR_ID,transport:TRANSPORT,state,project_title:extra.project_title??null,chat_title:extra.chat_title??null,browser:"Firefox Developer Edition",authority_effect:"NONE",observed_at:new Date().toISOString(),...extra})}
function journalFile(id){return path.join(dirs.journal,id+".json")}
function writeJournal(id,state,extra={}){const prev=readJson(journalFile(id),{});atomicJson(journalFile(id),{...prev,request_id:id,state,updated_at:new Date().toISOString(),...extra})}
let driver=null,binding=readJson(path.join(IPC,"binding.json"),null),relayEnabled=false;
async function visible(elements){for(const e of elements){try{if(await e.isDisplayed())return e}catch{}}return null}
async function findComposer(){for(const sel of ["#prompt-textarea","textarea","div[contenteditable='true'][data-lexical-editor='true']","div[contenteditable='true']"]){const e=await visible(await driver.findElements(By.css(sel)));if(e)return e}return null}
async function assistantTexts(){let rows=[];for(const sel of ["[data-message-author-role='assistant']","article[data-testid^='conversation-turn']"]){for(const e of await driver.findElements(By.css(sel))){try{if(await e.isDisplayed()){const t=(await e.getText()).trim();if(t)rows.push(t)}}catch{}}if(rows.length)break}return rows}
async function userTexts(){let rows=[];for(const e of await driver.findElements(By.css("[data-message-author-role='user']"))){try{if(await e.isDisplayed()){const t=(await e.getText()).trim();if(t)rows.push(t)}}catch{}}return rows}
async function bodyText(){try{return await driver.findElement(By.css("body")).getText()}catch{return ""}}
async function currentIdentity(){return {url:await driver.getCurrentUrl(),title:await driver.getTitle(),body:await bodyText(),composer:!!(await findComposer())}}
function chatIdentityVerified(id){return !!id && id.body.includes(EXPECTED_PROJECT) && (id.body.includes(EXPECTED_CHAT)||String(id.title||"").includes(EXPECTED_CHAT))}
async function ensureDriver(){if(driver)return;status("STARTING");let opts=new firefox.Options().setBinary(FIREFOX);opts.addArguments("-profile",PROFILE,"-no-remote");driver=await new Builder().forBrowser("firefox").setFirefoxOptions(opts).build();await driver.manage().setTimeouts({implicit:0,pageLoad:60000,script:30000});if(binding?.chat_url)await driver.get(binding.chat_url);else await driver.get("https://chatgpt.com/");}
async function updateHumanState(){const id=await currentIdentity();if(!id.composer){status("LOGIN_REQUIRED",{current_url:id.url});return false}if(!binding){status("PROJECT_BINDING_REQUIRED",{current_url:id.url});return false}if(!id.url.startsWith(binding.chat_url.split("?")[0])){try{await driver.get(binding.chat_url)}catch{};return false}const current=await currentIdentity();if(!chatIdentityVerified(current)){status("DEGRADED",{reason:"PROJECT_OR_CHAT_IDENTITY_MISMATCH",current_url:current.url});return false}status("READY",{project_title:binding.project_title,chat_title:binding.chat_title,current_url:current.url});return true}
async function processWork(file){const work=readJson(file);if(!work||work.transport!==TRANSPORT||!relayEnabled)return;const id=work.request_id,j=readJson(journalFile(id),{});if(j.state==="OUTBOX_WRITTEN")return;await driver.get(binding.chat_url);const beforeNow=await assistantTexts();const beforeCount=Number.isInteger(j.before_assistant_count)?j.before_assistant_count:beforeNow.length;writeJournal(id,j.state||"CLAIMED",{question_digest:work.question_digest,claim_generation:work.claim_generation,before_assistant_count:beforeCount});
 if(["SEND_TRIGGERED","USER_MESSAGE_OBSERVED","ASSISTANT_MESSAGE_OBSERVED"].includes(j.state)){/* recovery: never resend */}
 else {const comp=await findComposer();if(!comp)throw new Error("COMPOSER_NOT_FOUND");writeJournal(id,"NAVIGATED",{before_assistant_count:beforeCount});await comp.click();try{await comp.sendKeys(Key.CONTROL,"a",Key.BACK_SPACE)}catch{};await comp.sendKeys(work.question);writeJournal(id,"COMPOSER_WRITTEN");let sent=false;for(const sel of ["button[data-testid='send-button']","button[aria-label*='Send']","button[aria-label*='Wyślij']"]){const b=await visible(await driver.findElements(By.css(sel)));if(b){await b.click();sent=true;break}}if(!sent)await comp.sendKeys(Key.ENTER);writeJournal(id,"SEND_TRIGGERED");}
 const deadline=Date.now()+180000;let answer="",stable="",stableSince=0;while(Date.now()<deadline){const users=await userTexts();if(users.some(x=>x.includes(work.question.slice(0,Math.min(80,work.question.length)))))writeJournal(id,"USER_MESSAGE_OBSERVED");const after=await assistantTexts();if(after.length>beforeCount){const candidate=after[after.length-1].trim();if(candidate&&candidate===stable){if(!stableSince)stableSince=Date.now();if(Date.now()-stableSince>1800){answer=candidate;break}}else{stable=candidate;stableSince=Date.now()}}await new Promise(r=>setTimeout(r,500))}if(!answer)throw new Error("ASSISTANT_RESPONSE_TIMEOUT");writeJournal(id,"ASSISTANT_MESSAGE_OBSERVED",{response_sha256:crypto.createHash("sha256").update(answer).digest("hex")});atomicJson(path.join(dirs.outbox,id+".json"),{request_id:id,claim_generation:work.claim_generation,answer,model_identity:"ChatGPT UI / project "+binding.project_title,transport:TRANSPORT,authority_effect:"NONE"});writeJournal(id,"OUTBOX_WRITTEN");}
async function tick(){if(!relayEnabled)return;await ensureDriver();if(!(await updateHumanState()))return;const files=fs.readdirSync(dirs.inbox).filter(x=>x.endsWith(".json")).sort();for(const name of files){await processWork(path.join(dirs.inbox,name));break}}
const server=http.createServer(async(req,res)=>{res.setHeader("Access-Control-Allow-Origin","http://127.0.0.1:8780");res.setHeader("Access-Control-Allow-Headers","content-type");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");if(req.method==="OPTIONS"){res.writeHead(204);return res.end()}if(req.url==="/status"){res.setHeader("content-type","application/json");return res.end(JSON.stringify(readJson(path.join(IPC,"mediator-status.json"),{})))}if(req.method==="POST"&&req.url==="/control/open"){await ensureDriver();res.setHeader("content-type","application/json");return res.end(JSON.stringify({ok:true,status:readJson(path.join(IPC,"mediator-status.json"),{})}))}if(req.method==="POST"&&req.url==="/control/pin-current"){await ensureDriver();const id=await currentIdentity();let u;try{u=new URL(id.url)}catch{};if(!id.composer||!chatIdentityVerified(id)||!u||u.hostname!=="chatgpt.com"||!u.pathname.includes("/c/")){res.writeHead(409);return res.end(JSON.stringify({error:"exact project/chat/composer not verified"}))}binding={project_title:EXPECTED_PROJECT,chat_title:EXPECTED_CHAT,project_url:id.url,chat_url:id.url,bound_at:new Date().toISOString()};atomicJson(path.join(IPC,"binding.json"),binding);status(relayEnabled?"READY":"DISABLED",{project_title:EXPECTED_PROJECT,chat_title:EXPECTED_CHAT,current_url:id.url,reason:relayEnabled?undefined:"RELAY_OFF"});return res.end(JSON.stringify({ok:true,binding}))}if(req.method==="POST"&&req.url==="/control/relay/on"){relayEnabled=true;status("STARTING",{reason:"EXPLICIT_RELAY_ON"});await ensureDriver();return res.end('{"ok":true}')}if(req.method==="POST"&&req.url==="/control/relay/off"){relayEnabled=false;status("DISABLED",{reason:"RELAY_OFF"});return res.end('{"ok":true}')}res.writeHead(404);res.end('{"error":"not found"}')});
status("DISABLED",{reason:"RELAY_OFF"});
server.listen(8790,"127.0.0.1",()=>console.log("LION_FIREFOX_MEDIATOR_MANAGER 127.0.0.1:8790 · relay disabled until explicit operator action"));
(async()=>{while(true){try{await tick()}catch(e){status("DEGRADED",{reason:String(e.message||e).slice(0,300)});console.error(new Date().toISOString(),e)}await new Promise(r=>setTimeout(r,700))}})();
process.on("SIGINT",async()=>{status("STOPPED");try{if(driver)await driver.quit()}finally{process.exit(0)}});
