from __future__ import annotations

from dataclasses import dataclass
from typing import Final

ARCHITECTURE_LAYERS: Final = (
    "SYSTEM_CONTEXT",
    "CONSTITUTION_AND_GOVERNANCE",
    "EVIDENCE_AND_EPISTEMIC_PLANE",
    "EVOLUTIONARY_EPOCH",
    "GOVERNED_SELF_IMPLEMENTATION",
    "AUTHORITY_AND_EFFECT",
    "REPOSITORY_MUTATION",
    "FLEET_AND_SWARM",
    "TRUSTED_RUNTIME",
    "OBSERVABILITY_AND_RECONCILIATION",
    "CODE_PERCEPTION",
    "ARCHITECTURE_PROJECTION",
    "STARTUP_EVOLUTION",
    "TARGET_BEAN_FACTORY",
    "QUARANTINED_AND_NONCANONICAL",
)

FLOW_SPECS: Final = {
    "FLOW-01": ("WORLD", "OBSERVATION", "EVIDENCE", "HYPOTHESIS", "EXPERIMENT", "FALSIFICATION", "PROMOTION", "MEMORY", "EVOLUTION_DELTA"),
    "FLOW-02": ("EVOLUTION_DELTA", "GOVERNED_CHANGE_PROPOSAL", "BUILD_AUTHORIZATION", "BUILDER_ENTRY", "BUILDER_INVOCATION", "INVOCATION_CONSUMPTION", "START_ADMISSION", "PROCESS_LAUNCH", "DETACHED_CANDIDATE"),
    "FLOW-03": ("DETACHED_CANDIDATE", "INDEPENDENT_VERIFICATION", "AUTHORITY_LOOKUP", "POLICY_GATE", "CURRENTNESS", "EFFECT_ADMISSION", "EXACT_EFFECT", "OBSERVATION", "RECONCILIATION"),
    "FLOW-04": ("MISSION", "CAPABILITY_REQUIREMENTS", "SWARM_PLANNING", "ROLE_ALLOCATION", "EXECUTOR_PROVISIONING", "SANDBOX_BINDING", "RUNTIME_IDENTITY", "DISPATCH", "EXECUTION", "STATUS", "RECONCILIATION"),
    "FLOW-05": ("AUTHORITY_SOURCE", "ROOT_GRANT", "AUTHORITY_LINEAGE", "ATTENUATION", "REVOCATION_STATE", "PDP", "RUNTIME_CURRENTNESS", "PEP", "EFFECT"),
    "FLOW-06": ("REPOSITORY_BASELINE", "DETACHED_CHANGE", "EXACT_CANDIDATE_TREE", "VERIFICATION", "MERGE_AUTHORITY", "EFFECT_TIME_CURRENTNESS", "REF_MUTATION", "POST_EFFECT_OBSERVATION", "CLOSURE"),
    "FLOW-07": ("SOURCE_TREE", "STATIC_CODE_PERCEPTION", "SYMBOL_GRAPH", "ARCHITECTURE_PROJECTION", "CANONICAL_DIAGRAM_MODEL", "PUML", "OPTIONAL_RENDERED_ARTIFACT"),
    "FLOW-08": ("MARKET_EVIDENCE", "PRODUCT_HYPOTHESIS", "EXPERIMENT", "SMALLEST_BUILD", "LOCAL_CANDIDATE", "OUTCOME", "STARTUP_STATE_UPDATE"),
    "FLOW-09": ("GOAL", "WORLD_STATE", "SYSTEM_STATE", "GAP", "REQUIRED_CAPABILITY", "EXISTING_CAPABILITY_OR_NEW_BEAN", "COMPOSITION", "MOSAIC", "GOVERNED_EFFECT", "RECONCILED_OUTCOME"),
}


@dataclass(frozen=True, order=True)
class ArchitectureFlow:
    flow_id: str
    steps: tuple[str, ...]

    def validate(self) -> "ArchitectureFlow":
        if self.flow_id not in FLOW_SPECS:
            raise ValueError("unknown architecture flow")
        if self.steps != FLOW_SPECS[self.flow_id]:
            raise ValueError("architecture flow does not match canonical step order")
        if len(set(self.steps)) != len(self.steps):
            raise ValueError("architecture flow steps must be unique within a flow")
        return self


def canonical_flows() -> tuple[ArchitectureFlow, ...]:
    return tuple(ArchitectureFlow(flow_id, FLOW_SPECS[flow_id]).validate() for flow_id in sorted(FLOW_SPECS))
