const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {chromium}=require('C:/Users/d2j3/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const sourcePath=path.resolve(__dirname,'../app_coordination/local_intelligence_gateway.py');
const outputPath=process.argv[2]||path.resolve(__dirname,'../../../../outputs/lpcl-exact-source-browser.json');
const source=fs.readFileSync(sourcePath,'utf8');
const match=source.match(/UI=r'''([\s\S]*?)'''/);assert.ok(match);const html=match[1];
const required=`PROJECT=LION_EVOLUSION\nMODE=AUTONOMOUS_EXECUTE\nCONTROL_LANGUAGE=LPCL/1.2\nMISSION_ID=LION-LPCL-EXACT-SOURCE-CANARY-R1\nMISSION_TITLE=Exact Source Canary\nMISSION_OBJECTIVE=Verify exact source pinning\nMISSION_DESCRIPTION=Synthetic browser-only canary\nLOGICAL_DRONE_COUNT=128\nMATERIAL_DRONE_COUNT=64\nPROTOCOLS=LPCL,AUTHORITY,CURRENTNESS,EVIDENCE,VALIDATION,RECEIPT,CONTROL\nPHASE_01=VERIFY_EXACT_SOURCE|Verify exact source\nPHASE_01_EXECUTION_CLASS=VERIFY\nPHASE_01_CAPABILITY_CLASS=CONTROL_PLANE_RECONNAISSANCE\nPHASE_01_EFFECT_CEILING=NONE\nPHASE_01_BINDING_MODE=DYNAMIC\nPHASE_01_ON_MISSING_CAPABILITY=WAIT_AND_DISCOVER\nPHASE_01_AUTO_RESUME=TRUE\nPHASE_01_VERIFY_BEFORE_MUTATE=TRUE\nPHASE_01_CURRENTNESS=LIVE_PANEL\nPHASE_01_EVIDENCE=BROWSER_CANARY\nPHASE_01_COMPLETION_01=EXACT_SOURCE=PASS\n`;
const digest=s=>crypto.createHash('sha256').update(s).digest('hex');
const report={schema:'lion.lpcl-exact-source-browser/v1',source_sha256:digest(source),checks:{},requests:{validate:[],register:[],activate:[]},unexpected:[],page_errors:[],started_at:new Date().toISOString()};
let browser,registered=false;
(async()=>{try{
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1400,height:1000}});const page=await context.newPage();
 page.on('pageerror',e=>report.page_errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.addInitScript(()=>{window.setInterval=()=>1;});
 await page.route('**/*',async route=>{const req=route.request(),u=new URL(req.url()),p=u.pathname;if(u.origin!=='http://localhost'){report.unexpected.push(req.url());return route.abort()}
  let body={};
  if(p==='/')return route.fulfill({status:200,contentType:'text/html; charset=utf-8',body:html});
  if(p==='/api/state')body={model:'fixture',gpu:'fixture',rag_status:'fixture',web_capability:'fixture',repository_capability:'fixture',authority_effect:'NONE',material:{healthy:0},mission_control:{},supervisor_projection:{channel:'READY_FOR_HANDOFF',session:'EXPIRED',transport:'CHATGPT_SENTINELX_SESSION_MEDIATED',pending_count:0,pending_state:'NONE',last_receipt_state:'NONE',lease:{state:'EXPIRED'},authority:'NONE',automatic_hop:false,freshness:{state:'FRESH'},unknown_reasons:[]}};
  else if(p==='/api/missions/recent')body={missions:registered?[{mission_id:'LION-LPCL-EXACT-SOURCE-CANARY-R1',title:'Exact Source Canary',state:'REGISTERED',runtime_state:'NOT_STARTED',progress:0,current_phase:'VERIFY_EXACT_SOURCE'}]:[],focus_mission_id:registered?'LION-LPCL-EXACT-SOURCE-CANARY-R1':null};
  else if(p==='/api/missions/LION-LPCL-EXACT-SOURCE-CANARY-R1/process')body={mission_id:'LION-LPCL-EXACT-SOURCE-CANARY-R1',title:'Exact Source Canary',state:'REGISTERED',runtime_state:'NOT_STARTED',materialized:0,ready:0,process:{progress:0,current_phase:'VERIFY_EXACT_SOURCE'},phases:[],protocol_messages:[]};
  else if(p==='/api/threads'&&req.method()==='GET')body={threads:[{thread_id:'fixture-thread',title:'fixture'}]};
  else if(p==='/api/threads/fixture-thread')body={thread_id:'fixture-thread',title:'fixture',messages:[]};
  else if(p==='/api/lpcl/validate'&&req.method()==='POST'){const x=req.postDataJSON(),d=digest(x.lpcl_text);report.requests.validate.push(x);body={valid:true,lpcl_digest:d,source_currentness:{head:'a'.repeat(40),tree:'b'.repeat(40)},spec:{mission_id:'LION-LPCL-EXACT-SOURCE-CANARY-R1',title:'Exact Source Canary',objective:'Verify exact source pinning',description:'Synthetic browser-only canary',lpcl_digest:d,lpcl_text:x.lpcl_text,logical_count:128,material_target:64,phases:[{id:'VERIFY_EXACT_SOURCE',title:'Verify exact source'}],protocols:['LPCL','AUTHORITY','CURRENTNESS','EVIDENCE','VALIDATION','RECEIPT','CONTROL']}};}
  else if(p==='/api/lpcl/register'&&req.method()==='POST'){const x=req.postDataJSON(),d=digest(x.lpcl_text);report.requests.register.push(x);registered=true;body={idempotent:false,mission:{mission_id:'LION-LPCL-EXACT-SOURCE-CANARY-R1',spec_digest:d,process:{mission_id:'LION-LPCL-EXACT-SOURCE-CANARY-R1',lpcl_digest:d}},registration_confirmation:{mission_id:'LION-LPCL-EXACT-SOURCE-CANARY-R1',lpcl_digest:d,source_length:x.lpcl_text.length,authority_effect:'NONE'}};}
  else if(p==='/api/lpcl/activate'&&req.method()==='POST'){const x=req.postDataJSON();report.requests.activate.push(x);body={mission_id:x.mission_id,state:'RUNNING',runtime_state:'DRIVER_RUNNING',activation_confirmation:{mission_id:x.mission_id,lpcl_digest:x.lpcl_digest,authority_effect:'EXPLICIT_USER_ACTIVATION'}};}
  else {report.unexpected.push(req.method()+' '+p);return route.fulfill({status:404,contentType:'application/json',body:JSON.stringify({error:'unmocked'})})}
  return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
 });
 await page.goto('http://localhost/');await page.waitForFunction(()=>document.querySelector('#lpclText'));
 assert.equal(await page.locator('#lpclRegisterButton').isDisabled(),true);assert.equal(await page.locator('#lpclActivateButton').isDisabled(),true);
 const literal='Waliduj LPCLZarejestruj misjęAutoryzuj dokładny LPCL';await page.locator('#lpclText').fill(literal);await page.locator('#lpclValidateButton').click();
 assert.equal(report.requests.validate.length,0);assert.equal(await page.locator('#lpclStatus').innerText(),'LPCL INPUT NOT DETECTED');assert.match(await page.locator('#lpclPreview').innerText(),/"detected_key_count": 0/);report.checks.literal_rejected_locally={pass:true,network_validate_requests:0};
 await page.locator('#lpclText').fill(required);await page.locator('#lpclValidateButton').click();await page.waitForFunction(()=>document.querySelector('#lpclStatus').textContent.startsWith('VALID'));
 const d1=digest(required);assert.equal(report.requests.validate.length,1);assert.equal(report.requests.validate[0].lpcl_text,required);assert.equal(await page.locator('#lpclRegisterButton').isDisabled(),false);assert.equal(await page.locator('#lpclActivateButton').isDisabled(),true);
 const changed=required.replace('MISSION_TITLE=Exact Source Canary','MISSION_TITLE=Exact Source Canary Two');await page.locator('#lpclText').fill(changed);assert.match(await page.locator('#lpclStatus').innerText(),/DIRTY/);assert.equal(await page.locator('#lpclRegisterButton').isDisabled(),true);assert.equal(await page.locator('#lpclActivateButton').isDisabled(),true);assert.equal(await page.evaluate(()=>lpclValidated===null&&lpclRegistered===null),true);report.checks.input_drift_invalidates={pass:true};
 await page.locator('#lpclValidateButton').click();await page.waitForFunction(()=>document.querySelector('#lpclStatus').textContent.startsWith('VALID'));const d2=digest(changed);assert.notEqual(d1,d2);assert.equal(report.requests.validate.at(-1).lpcl_text,changed);
 await page.locator('#lpclRegisterButton').click();await page.waitForFunction(()=>document.querySelector('#lpclStatus').textContent.startsWith('REGISTERED'));assert.equal(report.requests.register.length,1);assert.equal(report.requests.register[0].lpcl_text,changed);assert.equal(await page.locator('#lpclValidateButton').isDisabled(),true);assert.equal(await page.locator('#lpclRegisterButton').isDisabled(),true);assert.equal(await page.locator('#lpclActivateButton').isDisabled(),false);report.checks.register_uses_frozen_source={pass:true,digest:d2};
 await page.locator('#lpclActivateButton').click();await page.waitForFunction(()=>document.querySelector('#lpclStatus').textContent.startsWith('AUTHORIZED'));assert.deepEqual(report.requests.activate,[{mission_id:'LION-LPCL-EXACT-SOURCE-CANARY-R1',lpcl_digest:d2}]);assert.equal(await page.locator('#lpclValidateButton').isDisabled(),true);assert.equal(await page.locator('#lpclRegisterButton').isDisabled(),true);assert.equal(await page.locator('#lpclActivateButton').isDisabled(),true);report.checks.authorize_exact_registered_digest={pass:true,digest:d2};
 assert.deepEqual(report.page_errors,[]);assert.deepEqual(report.unexpected,[]);report.result='PASS';
 }catch(e){report.result='FAIL';report.failure={name:e.name,message:e.message,stack:e.stack};process.exitCode=1}finally{if(browser)await browser.close();report.finished_at=new Date().toISOString();fs.mkdirSync(path.dirname(outputPath),{recursive:true});fs.writeFileSync(outputPath,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));}})();
