'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ThreadStore}=require('../src/thread-store');const {TurnReconciler}=require('../src/turn-reconciler');
function storeFor(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lion-r18-'));const db=path.join(dir,'threads.db');const s=new ThreadStore(db);t.after(()=>{try{s.close()}catch{}fs.rmSync(dir,{recursive:true,force:true})});return {s,db,dir};}
function bound(s,tid,rid='saas-r1'){s.bindRequest({thread_id:tid,request_id:rid,request_hash:'h-'+rid,provider_id:'CHATGPT_SAAS',context_digest:'c',question:'q',context_json:'{}',state:'PENDING'});return s.requestBinding(rid);}
test('T03 exactly one logical durable thread store instance owns one db handle',t=>{const {s}=storeFor(t);assert.ok(s.db);assert.equal(typeof s.db.prepare,'function');});
test('T09 request_id binds one exact thread and conflicting rebind fails',t=>{const {s}=storeFor(t),a=s.createThread('A'),b=s.createThread('B');bound(s,a.thread_id);assert.equal(s.requestBinding('saas-r1').thread_id,a.thread_id);assert.throws(()=>s.bindRequest({thread_id:b.thread_id,request_id:'saas-r1',request_hash:'h-saas-r1',provider_id:'CHATGPT_SAAS'}),/REQUEST_BINDING_CONFLICT/);});
test('T10 turn_id binds one exact request',t=>{const {s}=storeFor(t),a=s.createThread('A');bound(s,a.thread_id);s.bindTurn({request_id:'saas-r1',turn_id:'turn-a'});assert.equal(s.turnForRequest('saas-r1').turn_id,'turn-a');assert.throws(()=>s.bindTurn({request_id:'saas-r1',turn_id:'turn-b'}),/TURN_BINDING_CONFLICT/);});
test('T11 saas-user dedupe inserts once',t=>{const {s}=storeFor(t),a=s.createThread('A');const x=s.appendUserOnce(a.thread_id,'q','saas-user:r1'),y=s.appendUserOnce(a.thread_id,'q','saas-user:r1');assert.equal(x.inserted,true);assert.equal(y.inserted,false);assert.equal(s.getThread(a.thread_id).messages.length,1);});
test('T12 saas assistant dedupe inserts once',t=>{const {s}=storeFor(t),a=s.createThread('A');s.appendAssistantOnce(a.thread_id,'a','saas:r1');s.appendAssistantOnce(a.thread_id,'a','saas:r1');assert.equal(s.getThread(a.thread_id).messages.length,1);});
test('T13 duplicate receipt is immutable and cannot duplicate assistant',t=>{const {s}=storeFor(t),a=s.createThread('A');bound(s,a.thread_id);s.bindTurn({request_id:'saas-r1',turn_id:'turn-a'});s.recordReceipt({request_id:'saas-r1',turn_id:'turn-a',receipt_digest:'rec',response_digest:'resp'});s.recordReceipt({request_id:'saas-r1',turn_id:'turn-a',receipt_digest:'rec',response_digest:'resp'});assert.throws(()=>s.recordReceipt({request_id:'saas-r1',turn_id:'turn-a',receipt_digest:'other',response_digest:'resp'}),/RECEIPT_BINDING_CONFLICT/);s.appendAssistantOnce(a.thread_id,'answer','saas:saas-r1');s.appendAssistantOnce(a.thread_id,'answer','saas:saas-r1');assert.equal(s.getThread(a.thread_id).messages.length,1);});
test('T14 out of order receipt material remains request/thread isolated',t=>{const {s}=storeFor(t),a=s.createThread('A'),b=s.createThread('B');bound(s,a.thread_id,'ra');bound(s,b.thread_id,'rb');s.recordReceipt({request_id:'rb',receipt_digest:'B'});s.recordReceipt({request_id:'ra',receipt_digest:'A'});assert.equal(s.requestBinding('ra').thread_id,a.thread_id);assert.equal(s.requestBinding('rb').thread_id,b.thread_id);});
test('T15 two concurrent threads have isolated sequence and dedupe domains',t=>{const {s}=storeFor(t),a=s.createThread('A'),b=s.createThread('B');s.appendUserOnce(a.thread_id,'x','k');s.appendUserOnce(b.thread_id,'y','k');assert.equal(s.getThread(a.thread_id).messages[0].content,'x');assert.equal(s.getThread(b.thread_id).messages[0].content,'y');});
test('T16 deleted thread is tombstoned and cannot be resurrected',t=>{const {s}=storeFor(t),a=s.createThread('A');bound(s,a.thread_id);s.tombstoneThread(a.thread_id);assert.throws(()=>s.getThread(a.thread_id),/THREAD_NOT_FOUND/);assert.equal(s.requestBinding('saas-r1').state,'ORPHANED_THREAD');assert.throws(()=>s.appendAssistantOnce(a.thread_id,'late','saas:saas-r1'),/THREAD_NOT_FOUND/);});
test('T17 restart recovers pending request and turn bindings',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lion-r18-restart-')),db=path.join(dir,'threads.db');let s=new ThreadStore(db),a=s.createThread('A');bound(s,a.thread_id);s.bindTurn({request_id:'saas-r1',turn_id:'turn-a'});s.close();s=new ThreadStore(db);assert.equal(s.pendingBindings()[0].request_id,'saas-r1');assert.equal(s.turnForRequest('saas-r1').turn_id,'turn-a');s.close();fs.rmSync(dir,{recursive:true,force:true});});
test('T18 SEND_UNKNOWN is terminal-for-retry until explicit reconciliation',async t=>{const {s}=storeFor(t),a=s.createThread('A');bound(s,a.thread_id);s.markReconciliation('saas-r1','SEND_UNKNOWN','unknown');let called=0;const r=new TurnReconciler({store:s,missionControl:{requestStatus:async()=>{called++;}},relay:{},delivery:{}});const out=await r.runOnce();assert.equal(called,0);assert.equal(out[0].state,'SEND_UNKNOWN');});
test('T19 COMPLETION_UNKNOWN persists on failed exact turn readback',async t=>{const {s}=storeFor(t),a=s.createThread('A');bound(s,a.thread_id);s.bindTurn({request_id:'saas-r1',turn_id:'turn-a'});const r=new TurnReconciler({store:s,missionControl:{requestStatus:async()=>({status:'CLAIMED'})},relay:{getTurn:async()=>{throw Error('down')}},delivery:{}});await r.runOnce();assert.equal(s.reconciliation('saas-r1').state,'COMPLETION_UNKNOWN');});
test('T34 internal turn claim lease prevents double consumer inference',t=>{const {s}=storeFor(t),a=s.createThread('A');bound(s,a.thread_id);s.bindTurn({request_id:'saas-r1',turn_id:'turn-a'});const expiry=new Date(Date.now()+60000).toISOString();const x=s.claimTurn({turn_id:'turn-a',consumer_id:'c1',lease_id:'l1',lease_expiry:expiry}),y=s.claimTurn({turn_id:'turn-a',consumer_id:'c1',lease_id:'l1',lease_expiry:expiry});assert.equal(x.claim_epoch,1);assert.equal(y.idempotent,true);assert.throws(()=>s.claimTurn({turn_id:'turn-a',consumer_id:'c2',lease_id:'l2',lease_expiry:expiry}),/ALREADY_CLAIMED/);});
